server:
  port: 8080

spring:
  application:
  name: sample.securitybasic

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show-sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
          fetch_size: 500
          batch_versioned_data: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:security;MODE=MYSQL;
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    url: jdbc:h2:mem:security
    user: sa
    password:
    baseline-on-migrate: true

  devtools:
    add-properties: true
    restart:
      enabled: true

logging:
  config: classpath:logback.xml
  level:
    web: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    io.swagger.models.parameters.AbstractSerializableParameter: error

jwt:
  secret: eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4MTI4MzM3NywiaWF0IjoxNjgxMjgzMzc3fQ



