spring:
  profiles:
    active: test

server:
  port: 8080

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show-sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
          fetch_size: 500
          batch_versioned_data: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:security;MODE=MYSQL;
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    url: jdbc:h2:mem:security
    user: sa
    password:
    baseline-on-migrate: true

  devtools:
    add-properties: true
    restart:
      enabled: true

jwt:
  secret: eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IlZsd0V5VkJzWXQ5Vjd6cTU3VGVqTW5WVXl6YmxZY2ZQUXllMDhmN01HVkE5WGtIYSIsImV4cCI6MTY4MTExNDg1MywiaWF0IjoxNjgxMTE0ODUzfQ


